"""Ready-to-run command evaluator generated by Optimize Anything.

The fixed benchmark command must print one JSON object with a finite numeric
score and optional info object. Higher scores are better.
"""

from __future__ import annotations

from fnmatch import fnmatchcase
import json
import math
from pathlib import Path
import subprocess


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SEED_PROMPT_PATH = Path(".optimize-anything/prompts/native-engine-fps.txt")
SOLVER_INPUT = "Optimize the desktop/headless pokeemerald wasm2c engine for the official native-engine-fps evaluator. The benchmark opens no GUI and measures only WasmRunFrame: it independently replays into overworld, menu, and battle states, warms each for 10,007 frames, times exactly 1,000,003 engine frames, repeats two passes, and scores the arithmetic mean of aggregate scenario FPS. WasmRenderFrame runs only outside timing for committed start/end framebuffer hash checks. Any hash mismatch, nondeterminism, missing golden, or invalid timing scores 0.\n\nYou may edit only the allowlisted performance configuration, native engine core, and WASM compatibility headers. Do not edit or replace bench_main.c, run_bench.sh, bench_golden.json, replay inputs, Makefile, .optimize-anything, generated build files, or evaluator files. Do not weaken, bypass, hardcode, predict, or fake the correctness hashes or timer. Do not open a raylib window or any GUI. Preserve native-raylib compilation and do not change normal GBA or Kindle behavior.\n\nUse profiling/code inspection to choose one small, falsifiable optimization. Likely surfaces include native wasm2c compiler/linker flags in tools/native/performance.mk, semantics-preserving host BIOS shims in native_engine.c, and include/wasm compatibility primitives. Avoid fast-math or undefined-behavior flags unless you can justify bit-exact behavior. Do not run tools/native/run_bench.sh or the full official replay/benchmark yourself; the evaluator runs it exactly once after submission. Local checks must be bounded to a compile-only `make native-bench native-raylib` or similarly tiny smoke check. Never run Git commands. Call submit_artifact exactly once before ending, even if local checks are incomplete."
EDITABLE_PATHS = ["tools/native/performance.mk","tools/native/native_engine.c","tools/native/native_engine.h","include/wasm/**"]
BENCHMARK_COMMAND = ["bash","tools/native/run_bench.sh"]
BENCHMARK_TIMEOUT_SECONDS = 1200


def run_benchmark(workspace: Path) -> tuple[float, dict]:
    completed = subprocess.run(
        BENCHMARK_COMMAND,
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=BENCHMARK_TIMEOUT_SECONDS,
        check=False,
    )
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip()
        raise RuntimeError(f"Benchmark exited {completed.returncode}: {detail}")
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError(f"Benchmark stdout must be one JSON object: {error}") from error
    if not isinstance(payload, dict):
        raise RuntimeError("Benchmark stdout must be one JSON object")
    score = payload.get("score")
    if isinstance(score, bool) or not isinstance(score, (int, float)) or not math.isfinite(score):
        raise RuntimeError("Benchmark JSON score must be finite and numeric")
    info = payload.get("info", {})
    if not isinstance(info, dict):
        raise RuntimeError("Benchmark JSON info must be an object when provided")
    return float(score), info


def evaluate(submission: str) -> tuple[float, dict]:
    try:
        manifest = json.loads(submission)
        if not isinstance(manifest, dict):
            return -1e9, {"error": "submission must be a JSON object"}
        if manifest.get("valid") is not True:
            return -1e9, {"error": manifest.get("error", "invalid workspace")}
        changed_files = manifest.get("changedFiles")
        if not isinstance(changed_files, list) or not all(isinstance(path, str) for path in changed_files):
            return -1e9, {"error": "changedFiles must be a list of paths"}
        blocked = sorted(
            path for path in changed_files
            if not any(fnmatchcase(path, pattern) for pattern in EDITABLE_PATHS)
        )
        if blocked:
            return -1e9, {"error": f"Changes outside editable paths: {', '.join(blocked)}"}
        workspace = Path(manifest["workspace"])
        if not workspace.is_dir():
            return -1e9, {"error": f"Workspace does not exist: {workspace}"}
        return run_benchmark(workspace)
    except (KeyError, OSError, RuntimeError, ValueError, subprocess.TimeoutExpired) as error:
        return -1e9, {"error": str(error)}


def preflight() -> dict:
    score, info = run_benchmark(PROJECT_ROOT)
    return {"baseline_score": score, "info": info}


def build_task() -> dict:
    if not SEED_PROMPT_PATH.exists():
        raise FileNotFoundError(f"Create the seed prompt at {SEED_PROMPT_PATH.resolve()}")
    return {
        "seed_candidate": SEED_PROMPT_PATH.read_text(),
        "solver_input": SOLVER_INPUT,
        "evaluator": evaluate,
        "preflight": preflight,
        "objective": "Maximize the desktop pokeemerald wasm2c simulation engine throughput, scored as the arithmetic mean of aggregate headless WasmRunFrame FPS in overworld, menu, and battle scenarios, while preserving bit-exact rendered start/end framebuffer hashes and deterministic behavior.",
        "background": "Repository: pokeemerald decompilation with a WASM port converted to native C by wabt wasm2c on Darwin arm64. The protected headless benchmark is intentionally aligned with raylib's Internal FPS: it excludes software rendering from timed regions. Baseline is approximately 700,000 FPS on this host (roughly 550k overworld, 850k menu, 700k battle), with run-to-run noise normally under a few percent. Higher is better and there is no hard upper bound. The official benchmark builds from a fresh isolated worktree, runs two deterministic passes, aggregates fixed frame counts over wall-clock seconds, and requires six committed FNV-1a framebuffer hashes (start/end for three scenarios). Generated outputs live under ignored build/. Keep the benchmark and correctness oracle immutable. Project direction requires original GBA behavior and Kindle target to remain meaningful; desktop-only tuning belongs in tools/native/performance.mk or the native boundary.",
    }
